from . import meter_zones
from . import utility_meter
from . import res_partner
from . import crm_lead_inherit
from . import meter_serials
from . import meter_discounts
from . import meter_groups
from . import tariff_block
from . import tariff_range
from . import bill_plans
from . import meter_readings
from . import account_move_inherit
from . import res_users_inherit
from . import meter_reset
from . import meter_reset_history
from . import user_model_permission